#!/bin/bash

set -e
set -x

sudo openconnect --background asa1.uni-saarland.de
sleep 1

# Correct the MTU setting of the tunneling device.  For more information, see
# https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1254085/comments/9
sudo ip link set mtu 1200 dev tun0
